@echo off
echo Activating virtual environment...
call venv\Scripts\activate

echo Installing Python dependencies...
pip install -r requirements.txt

echo Changing directory to dbt...
cd dbt

echo Step 1: Running dbt to build staging models...
dbt run 

echo Step 2: Generating apartment scores CSV...
python ..\scripts\generate_apartment_scores.py

echo Step 3: Seeding CSV to Snowflake...
dbt seed

echo Step 4: Running dbt again to build final models...
dbt run

echo All done! Apartment pipeline finished.
