version: 2

sources:
  - name: subway_data
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: raw_subway_data
      
  - name: apartment_data
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: raw_apartment_data

  - name: neighborhood_data
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: raw_neighborhood_data

  - name: apartment_data_transformed
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: dim_apartment
      - name: fct_apartment_scores
  - name: airbyte
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: listings


