version: 2

sources:
  - name: subway_data
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: nyc_transit_data
      
  - name: apartment_data
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: apartment_listings
  - name: neighborhood_data
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: zipcodes_safety_grades_nyc

#  - name: my_model
#    config:
#      materialized: table
      #target_name: "{{ target.name }}"
      #specific_var: "{{ var('SPECIFIC_VAR') }}"
      #specific_env_var: "{{ env_var('SPECIFIC_ENV_VAR') }}"


